# Generated by Django 4.2.2 on 2023-08-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Our_datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=25)),
                ('Dob', models.CharField(default='', max_length=12)),
                ('Age', models.IntegerField(default='', max_length=3)),
                ('Gender', models.CharField(default='', max_length=10)),
                ('State', models.CharField(default='', max_length=18)),
                ('Email', models.CharField(default='', max_length=12)),
                ('Contact', models.CharField(default='', max_length=18)),
            ],
        ),
    ]
